version: 0.0
os: linux

files:
  - source: /
    destination: /home/ec2-user/nest-back
permissions:
  - object: /home/ec2-user
    pattern: '**'
    owner: root
    group: root
hooks:
  BeforeInstall:
    - location: scripts/before_deploy.sh
      runas: root
  AfterInstall:
    - location: scripts/after_deploy.sh
      runas: root