version: 0.0
os: linux

files:
  - source: /
    destination: /home/ec2-user/nest-back
permissions:
  - object: /home/ec2-user
    pattern: '**'
    owner: ec2-user
    group: ec2-user
hooks:
  BeforeInstall:
    - location: scripts/before_deploy.sh
      runas: ec2-user
  AfterInstall:
    - location: scripts/after_deploy.sh
      runas: ec2-user